### PR TITLE
Issue #126 Sort the features

### PR DESCRIPTION
**Pull request by mjethanandani**
First crack at sorting the feature set. Issue #126

### CODE REVIEW

**Review by keyur-arrcus — APPROVED** [review]

**Comment by jhaas-pfrc** [comment]
I believe I've pulled the branch in question and the features aren't sorted?

**Comment by mjethanandani** [comment]
> I believe I've pulled the branch in question and the features aren't sorted?

@jhaas-pfrc , maybe you could expand on how do you see the features as being sorted. Alphabetically?? Or something else??

**Comment by jhaas-pfrc** [comment]
With e7b279661e9aee53b9bb9027d7ae8b935d459b50 applied here's the order I see:
route-refresh
damping
ttl-security
graceful-restart
bfd
add-paths
send-comunities
clear-neighbors...

**Comment by mjethanandani** [comment]
> With [e7b2796](https://github.com/mjethanandani/ietf-bgp-yang/commit/e7b279661e9aee53b9bb9027d7ae8b935d459b50) applied here's the order I see:
> route-refresh
> damping
> ttl-security
> graceful-restart
> bfd
> add-paths
> send-comunities
> clear-neighbors...

That is correct. Did you want to see a different order? If so, what order are you looking for.

**Comment by jhaas-pfrc** [comment]
Lexicographical ordering is what one usually means when the word sort is used.  However, I'm curious what sort order is implemented in the current diff?

**Pull request merged**
