### PR TITLE
Issue #300 - add-paths is missing at afi-safis level configuration

### LINKED ISSUE #300: add-paths is missing at afi-safis level configuration
Noted as art of review in Issue #292

### PR DESCRIPTION
**Pull request by jhaas-pfrc**
Closes #300

### CODE REVIEW

**Comment by jhaas-pfrc** [comment]
Partially addresses Issue #292

**Review by mjethanandani — COMMENTED** [review]
This is more for my education.

The comment in the grouping says that it is used to include ADD-PATHs configuration for neighbors and peer-groups. As I see the change, the first addition applies it at a global level. Is this applicable at a global level? If so, should the description of the grouping reflect that?

**Comment by jhaas-pfrc** [comment]
> This is more for my education.
> 
> The comment in the grouping says that it is used to include ADD-PATHs configuration for neighbors and peer-groups. As I see the change, the first addition applies it at a global level. Is this applicable at a global level? If so, should the description of the grouping reflect that?

Good point.  Let me ponder if the better answer is to update grouping name/description or whether further work needs to bedone.

**Comment by jhaas-pfrc** [comment]
> This is more for my education.
> 
> The comment in the grouping says that it is used to include ADD-PATHs configuration for neighbors and peer-groups. As I see the change, the first addition applies it at a global level. Is this applicable at a global level? If so, should the description of the grouping reflect that?

So, global afi/safi support for add-paths is in the OC model, partially because of Cisco support:
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus3548/sw/unicast/6x/b_Cisco_Nexus_3548_Unicast_Routing_Configuration_Guide_Release_6_x/b_Cisco_Nexus_3548_Unicast_Routing_Configuration_Guide_Release_6_x_chapter_0111.pdf

Juniper only supports it at the group and neighbor level:
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/add-path-edit-protocols-bgp.html

Arista has support for global add-paths as well.
https://www.arista.com/en/um-eos/eos-border-gateway-protocol-bgp

**Comment by jhaas-pfrc** [comment]
I'm making the call that global afi/safi will be included.  Juniper will have to deviate.

Please review the name change and if we're good, we can merge.

Partially addresses Issue #292

**Review by mjethanandani — APPROVED** [review]

**Comment by suehares** [comment]
https://forum.huawei.com/enterprise/en/multiple-paths-for-the-same-prefix-to-be-advertised-in-bgp/thread/592456-861

Shows an example of Huawei at AFI/SAFI level.  This adds this input to the trouble ticket.    it does not need to be opened again.

**Pull request merged**
